---

- name: Update NIC to ONBOOT=yes
  shell: perl -pi -e 's/ONBOOT\=no/ONBOOT\=yes/g' /etc/sysconfig/network-scripts/ifcfg-eth1
  when: ansible_distribution == 'CentOS'

- name: restart network service
  service: name=network state=restarted

- name: Copy hosts template to entire cluster
  template: src=roles/cluster/templates/hosts.j2 dest=/etc/hosts
  tags:
     - host

- name: Add Kubernetes repo
  template: src=roles/cluster/templates/kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo force=yes

- name: install docker
  yum: name=docker state=latest

- name: install kubelet
  yum: name=kubelet state=latest

- name: install kubeadm
  yum: name=kubeadm state=latest

- name: install kubectl
  yum: name=kubectl state=latest

- name: install kubernetes-cni
  yum: name=kubernetes-cni state=latest

- name: start and enable docker service.
  service: name=docker state=started enabled=yes

- name: start and enable kubelet service.
  service: name=kubelet state=started enabled=yes