---

- name: fetch contiv
  shell: wget {{contiv_url}} -O /home/{{user_account}}/contiv.tgz
  tags:
    - fetch

- file:
    path: /home/{{user_account}}/contiv
    state: directory

- name: unzip contiv
  shell: tar xf contiv.tgz -C contiv --strip-components=2
  tags:
    - untar

- name: Update permissions back to user_account
  shell: chown -R {{user_account}}:{{user_account}} /home/{{user_account}}/contiv/*

- name: Update contiv.yml netmaster IP with eth0 NIC
  shell: perl -pi -e 's/__NETMASTER_IP__/{{ hostvars[inventory_hostname]['ansible_eno16777984']['ipv4']['address'] }}/g' /home/{{user_account}}/contiv/install/k8s/contiv.yaml

- name: Update contiv_config.yml netmaster IP with eth0 NIC
  shell: perl -pi -e 's/__NETMASTER_IP__/{{ hostvars[inventory_hostname]['ansible_eno16777984']['ipv4']['address'] }}/g' /home/{{user_account}}/contiv/install/k8s/contiv_config.yaml

- name: Update contiv.yml interface for BGP with eth1 NIC
  shell: perl -pi -e 's/__VLAN_IF__/eno33557248/g' /home/{{user_account}}/contiv/install/k8s/contiv.yaml
