---

# - name: fetch official Contiv repo
#   git:
#     repo: https://github.com/contiv/netplugin.git
#     dest: /home/{{user_account}}/netplugin
#     force: yes

- name: fetch contiv
  get_url:
    url: "{{contiv_url}}"
    dest: /home/{{user_account}}/contiv
    force: yes
  tags:
    - fetch
# - name: untar contiv
#   unarchive:
#     src: /home/{{user_account}}
#     dest: /home/{{user_account}}
#     remote_src: False
# - name: Update permissions back to user_account
#   shell: chown -R {{user_account}}:{{user_account}} netplugin/

# - name: Update contiv.yml netmaster IP
#   shell: perl -pi -e 's/__NETMASTER_IP__/{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}/g' /home/{{user_account}}/netplugin/install/k8s/contiv/contiv.yaml


# - name: Update contiv.yml interface for BGP
#   shell: perl -pi -e 's/__VLAN_IF__/eth1/g' /home/{{user_account}}/netplugin/install/k8s/contiv/contiv.yaml
