---

- name: Install Ansible on Control node
  yum: name=ansible state=latest
  
- name: Install bzip2 on Control node
  yum: name=bzip2 state=latest  

- name: Install python-netaddr on Control node
  yum: name=python-netaddr state=latest

- name: Install Git on Control node
  yum: name=git state=latest 

- name: Install PIP on Control node
  yum: name=python-pip state=latest

- name: Copy hosts template to Control node
  template: src=roles/control_node/templates/hosts dest=/etc/hosts

- name: Grab official Contiv repo
  git:
    repo: https://github.com/contiv/demo.git
    dest: /home/{{user_account}}/contiv
    force: yes


- name: Grab repo that contains the k8s info.
  shell: git clone https://github.com/jojimt/contrib -b contiv
  args:
    chdir: contiv/k8s

- name: Create cluster_defs.json
  template: src=roles/control_node/templates/cluster_template.j2 dest=/home/{{user_account}}/contiv/k8s/cluster_defs.json
  tags:
    - cluster_template

- name: Update permissions back to user_account
  shell: chown -R {{user_account}}:{{user_account}} contiv/

