---

- name: Install Ansible on Control node
  yum: name=ansible state=latest
  
- name: Install bzip2 on Control node
  yum: name=bzip2 state=latest  

- name: Install Git on Control node
  yum: name=git state=latest 

- name: Install PIP on Control node
  yum: name=python-pip state=latest

- name: Copy hosts template to Control node
  template: src=roles/control_node/templates/hosts dest=/etc/hosts


# - user:
#     name: "{{user_account}}"
#     generate_ssh_key: yes
#     ssh_key_bits: 2048
#     ssh_key_file: .ssh/id_rsa

# - name: Downloading pub key
#   fetch: src=/home/{{user_account}}/.ssh/id_rsa.pub dest=roles/control_node/templates/id_rsa.tmp flat=yes

# - name: Copying local key to workers
#   local_action: shell cat roles/control_node/templates/id_rsa.tmp | ssh {{user_account}}@{{item}} "cat >> /home/{{user_account}}/.ssh/authorized_keys"
#   with_items: "{{groups['workers']}}"

# - name: Deleting temporal files
#   local_action: file  path=roles/control_node/templates/id_rsa.tmp state=absent


